# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\semester 6\DSP\tasks\PROJECTTTTT\Signal_Viewer-main\dsp1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 601)
        MainWindow.setStyleSheet("background-color: rgb(102, 120, 199);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.Spectogram_label = QtWidgets.QLabel(self.centralwidget)
        self.Spectogram_label.setGeometry(QtCore.QRect(650, 10, 141, 31))
        self.Spectogram_label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);\n"
"")
        self.Spectogram_label.setObjectName("Spectogram_label")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(160, 50, 741, 311))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.signals_plot_widget = PlotWidget(self.splitter_2)
        self.signals_plot_widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.signals_plot_widget.setObjectName("signals_plot_widget")
        self.Spectogram_plot_widget = QtWidgets.QWidget(self.splitter_2)
        self.Spectogram_plot_widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Spectogram_plot_widget.setObjectName("Spectogram_plot_widget")
        self.channel_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.channel_combobox.setGeometry(QtCore.QRect(690, 370, 101, 21))
        self.channel_combobox.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.channel_combobox.setObjectName("channel_combobox")
        self.channel_combobox.addItem("")
        self.channel_combobox.addItem("")
        self.channel_combobox.addItem("")
        self.Controls_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Controls_groupBox.setGeometry(QtCore.QRect(0, 410, 931, 191))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Controls_groupBox.setFont(font)
        self.Controls_groupBox.setStyleSheet("\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.Controls_groupBox.setObjectName("Controls_groupBox")
        self.stop_button = QtWidgets.QPushButton(self.Controls_groupBox)
        self.stop_button.setGeometry(QtCore.QRect(80, 30, 75, 31))
        self.stop_button.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.stop_button.setObjectName("stop_button")
        self.play_button = QtWidgets.QPushButton(self.Controls_groupBox)
        self.play_button.setGeometry(QtCore.QRect(10, 30, 75, 31))
        self.play_button.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.play_button.setObjectName("play_button")
        self.zoom_IN_button = QtWidgets.QPushButton(self.Controls_groupBox)
        self.zoom_IN_button.setGeometry(QtCore.QRect(150, 30, 81, 31))
        self.zoom_IN_button.setMinimumSize(QtCore.QSize(81, 23))
        self.zoom_IN_button.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.zoom_IN_button.setObjectName("zoom_IN_button")
        self.zoom_OUT_button = QtWidgets.QPushButton(self.Controls_groupBox)
        self.zoom_OUT_button.setGeometry(QtCore.QRect(230, 30, 91, 31))
        self.zoom_OUT_button.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.zoom_OUT_button.setObjectName("zoom_OUT_button")
        self.layoutWidget = QtWidgets.QWidget(self.Controls_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(500, 50, 101, 84))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Speed_label = QtWidgets.QLabel(self.layoutWidget)
        self.Speed_label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.Speed_label.setObjectName("Speed_label")
        self.verticalLayout_2.addWidget(self.Speed_label)
        self.SignalSpeed_horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.SignalSpeed_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SignalSpeed_horizontalSlider.setObjectName("SignalSpeed_horizontalSlider")
        self.verticalLayout_2.addWidget(self.SignalSpeed_horizontalSlider)
        self.layoutWidget_2 = QtWidgets.QWidget(self.Controls_groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(640, 50, 101, 121))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.minimum = QtWidgets.QLabel(self.layoutWidget_2)
        self.minimum.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.minimum.setObjectName("minimum")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.minimum)
        self.minimum_verticalSlider = QtWidgets.QSlider(self.layoutWidget_2)
        self.minimum_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.minimum_verticalSlider.setObjectName("minimum_verticalSlider")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.minimum_verticalSlider)
        self.maximum_verticalSlider = QtWidgets.QSlider(self.layoutWidget_2)
        self.maximum_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.maximum_verticalSlider.setObjectName("maximum_verticalSlider")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maximum_verticalSlider)
        self.maximum = QtWidgets.QLabel(self.layoutWidget_2)
        self.maximum.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.maximum.setObjectName("maximum")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maximum)
        self.pushButton = QtWidgets.QPushButton(self.Controls_groupBox)
        self.pushButton.setGeometry(QtCore.QRect(300, 140, 181, 23))
        self.pushButton.setObjectName("pushButton")
        self.hidesignals_checkbox = QtWidgets.QCheckBox(self.Controls_groupBox)
        self.hidesignals_checkbox.setGeometry(QtCore.QRect(30, 80, 111, 21))
        self.hidesignals_checkbox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.hidesignals_checkbox.setObjectName("hidesignals_checkbox")
        self.label_3 = QtWidgets.QLabel(self.Controls_groupBox)
        self.label_3.setGeometry(QtCore.QRect(620, 20, 191, 31))
        self.label_3.setObjectName("label_3")
        self.Select_Colur_button = QtWidgets.QPushButton(self.Controls_groupBox)
        self.Select_Colur_button.setGeometry(QtCore.QRect(144, 80, 131, 23))
        self.Select_Colur_button.setObjectName("Select_Colur_button")
        self.Signals_label = QtWidgets.QLabel(self.centralwidget)
        self.Signals_label.setGeometry(QtCore.QRect(290, 10, 91, 31))
        self.Signals_label.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.Signals_label.setObjectName("Signals_label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 370, 131, 20))
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.label_2.setObjectName("label_2")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(160, 360, 371, 20))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(140, 49, 20, 301))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 47, 13))
        self.label_4.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 280, 47, 13))
        self.label_5.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 47, 13))
        self.label_8.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font:(255,255,255);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(60, 190, 71, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(60, 280, 71, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 100, 71, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Spectogram_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Spectrogram</span></p></body></html>"))
        self.channel_combobox.setItemText(0, _translate("MainWindow", "channel1"))
        self.channel_combobox.setItemText(1, _translate("MainWindow", "channel2"))
        self.channel_combobox.setItemText(2, _translate("MainWindow", "channel3"))
        self.Controls_groupBox.setTitle(_translate("MainWindow", "Controls"))
        self.stop_button.setText(_translate("MainWindow", "stop"))
        self.play_button.setText(_translate("MainWindow", "play"))
        self.zoom_IN_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.zoom_IN_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>dsds</p></body></html>"))
        self.zoom_IN_button.setText(_translate("MainWindow", "zoom in"))
        self.zoom_OUT_button.setText(_translate("MainWindow", "zoom out"))
        self.Speed_label.setText(_translate("MainWindow", "speed"))
        self.minimum.setText(_translate("MainWindow", "min"))
        self.maximum.setText(_translate("MainWindow", "max"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.hidesignals_checkbox.setText(_translate("MainWindow", "hide signals"))
        self.label_3.setText(_translate("MainWindow", "Spectrogram range"))
        self.Select_Colur_button.setText(_translate("MainWindow", "select colour"))
        self.Signals_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Signals</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "select channel :"))
        self.label_4.setText(_translate("MainWindow", "channel 2"))
        self.label_5.setText(_translate("MainWindow", "channel 3"))
        self.label_8.setText(_translate("MainWindow", "channel 1"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
